import { readFile } from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import type { EditionFile, EditionContext } from './rosterAdapters.js';
import { editionFileTarget } from './rosterAdapters.js';
import { hashBuffer } from './hash.js';

const json=(value:unknown):Buffer=>Buffer.from(JSON.stringify(value,null,2)+'\n');
/** Bind final generated bytes to a bounded integrity inventory, without executing research. */
export async function addScientificIntegrity(files:EditionFile[],context:EditionContext):Promise<void>{
  const prefix='runtime/research-specialists/';
  if(!files.some(f=>f.relativePath.startsWith(prefix)))return;
  const replace=(name:string,content:Buffer)=>{const relativePath=prefix+name,index=files.findIndex(f=>f.relativePath===relativePath);const f={id:`scientific/${name}`,type:'hook' as const,relativePath,sourcePath:'canonical-scientific-runtime',content};if(index>=0)files[index]=f;else files.push(f);};
  let pythonExecutable:string|null=null,pythonVersion:string|null=null;
  if(!context.portable){
    for(const candidate of [path.join(context.runtimeRoot,'research-specialists/runtime.json'),path.join(process.env.USERPROFILE??os.homedir(),'.codex/research-specialists/runtime.json')]){
      try{const prior=JSON.parse(await readFile(candidate,'utf8'));if(typeof prior.pythonExecutable==='string'&&path.isAbsolute(prior.pythonExecutable)){pythonExecutable=prior.pythonExecutable;pythonVersion=prior.pythonVersion??null;break;}}catch{/* Metadata may be absent on a fresh workstation. */}
    }
  }
  replace('runtime.json',json({pythonExecutable,pythonVersion,sessionDataRoot:path.resolve(context.runtimeRoot,'..','state/research'),executionVerified:false,status:pythonExecutable?'existing-interpreter-metadata':'interpreter-not-configured'}));
  const roots=[context.agentRoot,context.skillRoot,context.runtimeRoot,...context.hooksRoot?[context.hooksRoot]:[]].map(p=>path.resolve(p));
  replace('scripts/research-integrity.mjs',Buffer.from(`// Generated from the common edition integrity contract. No agent regeneration or profile discovery.
import {createHash} from 'node:crypto';
import {lstat,readFile,realpath} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const SCOPES=${JSON.stringify(roots)};
const hash=b=>createHash('sha256').update(b).digest('hex');
const norm=p=>process.platform==='win32'?path.resolve(p).toLowerCase():path.resolve(p);
const inside=(root,p)=>{const r=path.relative(norm(root),norm(p));return !!r&&!path.isAbsolute(r)&&r!=='..'&&!r.startsWith('..'+path.sep);};
async function bounded(root,file){
 if(!inside(root,file)||!inside(await realpath(root),await realpath(file)))throw new Error('Integrity path escapes owned scope');
 let cursor=file;while(norm(cursor)!==norm(root)){const s=await lstat(cursor);if(s.isSymbolicLink())throw new Error('Integrity path uses a symbolic link');cursor=path.dirname(cursor);}
 const stat=await lstat(file);if(!stat.isFile()||stat.size>8*1024*1024)throw new Error('Integrity resource exceeds limit');return readFile(file);
}
export async function verifyResearchPackageIntegrity(root=ROOT){
 let bytes;try{bytes=await bounded(root,path.join(root,'package-integrity.json'));}catch(e){if(e.code==='ENOENT')return {status:'not-installed',verifiedFiles:0};throw e;}
 if(bytes.length>1024*1024)throw new Error('Inventory exceeds limit');const inv=JSON.parse(bytes);
 if(inv.version!==1||inv.format!=='agent-forge-edition-research-v1'||!Array.isArray(inv.files)||!inv.files.length||inv.files.length>2000||!Array.isArray(inv.generatedDefinitions)||!inv.generatedDefinitions.length||inv.generatedDefinitions.length>10000)throw new Error('Invalid integrity inventory');
 const seen=new Set();let total=0;
 for(const f of inv.files){if(typeof f.path!=='string'||/[\\\\:\\x00-\\x1f]/.test(f.path)||f.path.split('/').some(s=>!s||s==='.'||s==='..')||f.path==='package-integrity.json'||seen.has(f.path.toLowerCase())||!/^[a-f0-9]{64}$/.test(f.sha256))throw new Error('Invalid integrity resource');seen.add(f.path.toLowerCase());const data=await bounded(root,path.resolve(root,f.path));total+=data.length;if(hash(data)!==f.sha256)throw new Error('Scientific resource changed');}
 for(const required of ['runtime.json','scripts/research-session.mjs','scripts/research-hooks.mjs','scripts/research-integrity.mjs','scripts/run-research-python.mjs'])if(!seen.has(required))throw new Error('Required scientific runtime missing');
 const definitions=new Set();for(const f of inv.generatedDefinitions){if(typeof f.path!=='string'||!path.isAbsolute(f.path)||definitions.has(norm(f.path))||!/^[a-f0-9]{64}$/.test(f.sha256))throw new Error('Invalid definition');definitions.add(norm(f.path));const scope=SCOPES.find(s=>inside(s,f.path));if(!scope)throw new Error('Definition outside scopes');const data=await bounded(scope,f.path);total+=data.length;if(hash(data)!==f.sha256)throw new Error('Scientific definition changed');}
 if(total>128*1024*1024||inv.packageHash!==hash(JSON.stringify({files:inv.files,generatedDefinitions:inv.generatedDefinitions})))throw new Error('Integrity digest or size mismatch');
 return {status:'verified',verifiedFiles:inv.files.length,verifiedDefinitions:inv.generatedDefinitions.length};
}
`));
  const packageFiles=files.filter(f=>f.relativePath.startsWith(prefix)&&!f.relativePath.endsWith('/package-integrity.json')).map(f=>({path:f.relativePath.slice(prefix.length),sha256:hashBuffer(f.content)})).sort((a,b)=>a.path.localeCompare(b.path));
  const generatedDefinitions=files.filter(f=>!f.relativePath.startsWith(prefix)&&!f.relativePath.endsWith('/catalog.json')).map(f=>({path:editionFileTarget(f,context),sha256:hashBuffer(f.content)})).sort((a,b)=>a.path.localeCompare(b.path));
  replace('package-integrity.json',json({version:1,format:'agent-forge-edition-research-v1',files:packageFiles,generatedDefinitions,packageHash:hashBuffer(Buffer.from(JSON.stringify({files:packageFiles,generatedDefinitions})))}));
}
